# Generated by Django 5.0.7 on 2024-08-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('techemail', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('techrole', models.CharField(max_length=100)),
                ('profile', models.FileField(upload_to='static\\Bookedprofiles')),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'ServiceBookingModel',
            },
        ),
    ]
