# Generated by Django 5.0.7 on 2024-08-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_servicebookingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
            ],
            options={
                'db_table': 'FeedbackModel',
            },
        ),
    ]
