# Generated by Django 5.0.7 on 2024-08-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedbackmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackModel',
        ),
        migrations.AddField(
            model_name='servicebookingmodel',
            name='feedback',
            field=models.TextField(default='None', null=True),
        ),
    ]
