# Generated by Django 5.0.7 on 2024-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_feedbackmodel_servicebookingmodel_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'ContactUsModel',
            },
        ),
    ]
